spring:
  application:
    name: AskMyDoc

  datasource:
#    url: jdbc:postgresql://localhost:5432/askmydoc
#    username: admin
#    password: admin123
    url: ${DB_URL:jdbc:postgresql://localhost:5432/askmydoc}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}  
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

gemini:
  apiBase: https://generativelanguage.googleapis.com/v1beta
  apiKey: ${GEMINI_API_KEY}
  modelText: models/gemini-2.5-flash
  modelEmbedding: models/text-embedding-004

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

server:
  port: 8080