spring:
  application:
    name: AskMyDoc

  datasource:
    url: jdbc:postgresql://localhost:5432/askmydoc
    username: postgres
    password: yusuf@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false


gemini:
  apiBase: https://generativelanguage.googleapis.com/v1beta
  apiKey: ${GEMINI_API_KEY}
  modelText: gemini-1.5-flash
  modelEmbedding: models/text-embedding-004

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

server:
  port: 8082
